### ISSUE TITLE
Shake off a bit of dust, make it backwards compatible?

### ISSUE THREAD

**Issue by tehKaiN** [msharov/iff#1]
Hi there, is this still alive? ;)

As I'm developing my game engine for Amiga, I thought that I should support IFF files for my gfx assets. In runtime I'm using custom lightweight bitplane format, but still I have a tool for converting to it from PNG. IFF started to be an asked feature from my fellow Amigans and your library looks as a good starting point code- and license-wise. Unfortunately I can't really use it out of the box:

- I really need support for reading/writing old IFFs, so I thought this library could be parametrized regarding endian and alignment thingy. Perhaps as some kind of template-passed function of endian conversion compatible with `std::endian` on newer compilers, and a grain number? For non-native grain it would use memcpy and for native just copying - perhaps it's doable?
- also I need to add a CMake support for nicely integrating with my engine. I tried get a grip of automake many times but we don't like each other unfortunately.
- also I see it depends on uSTL which you deprecated, so rewriting to pure STL would be useful, I think.

Those are issues which need splitting into 3 separate ones, but I thought I'll ask in one place first. Of course i know a bit of C++, so I can try to tackle those changes myself, but I'd appreciate your guidance as you know this code better than me, and also I wonder if you'd be interested in merging those changes eventually.

Just for sake of completeness, issue on my end: https://github.com/AmigaPorts/ACE/issues/69

**Comment by msharov** [comment]
I admit this project has been dead for years. I last used it back in, oh, 2007 or so, and have only been keeping it updated to compile with current gcc. For some reason, I didn't even get any notification that you opened this issue.

There are a couple of reasons why the changes you suggest probably won't be acceptable. First, is the uSTL dependency, which can not be removed because of libiff is built on top of uSTL's binary streams. There is no equivalent to that in the standard library. uSTL has been deprecated because people kept trying to use it as a drop-in replacement for the standard library and, of course, failing, since it is not designed for that. For my own use I intend to transition to the [cwiclo library](https://github.com/msharov/cwiclo) I am currently writing, which expressly disavows any standard library compatibility. Unfortunately, that is not ready for release yet.

Regarding the parametrization of endianness and alignment, I am not quite clear what you are asking here. Adding a template parameter would still bake the choice into the code, much like the build options do now. If you really intend to support reading and writing all possible types of iff files, that would require runtime parameters, determined when the file is read. I did not do it that way to keep the code simple and small, and additional parameters and loading logic rather break that desire. Today I no longer use the library and am no longer opposed to making these changes.

CMake is out of the question. This drive toward fancy build systems is entirely unnecessary and simply substitutes one set of problems for another. And, there is no reason for you to care about this in the first place; libiff is supposed to be compiled, installed, and linked to, not embedded in your project tree.

Which brings us to the issue of your ACE project, which is written in C and has unusual target platforms (Amiga?). You obviously can't link to a C++ library, so you must be trying to copy and adapt some libiff code rather than linking to the library. If this is the case, there is no point of making the changes you suggest to libiff. I will certainly not be rewriting it in C, but you are of course welcome to cut-n-paste and adapt whatever code you see useful.

While doing that, you may find it useful to also copy some code from my [casycom project](https://github.com/msharov/casycom), which has a binary streams implementation in C (in [stm.h](https://github.com/msharov/casycom/blob/master/stm.h)) that could replace uSTL streams in your adaptation. Good luck with your port!

**Comment by tehKaiN** [comment]
Nah, ACE is in C (yet), but utils for generating semi-raw data files are written in recent C++ mixed with some C libs. Now that I think of, that template stuff I proposed was a brain fart, indeed runtime switches are more desired. CMake is quite old build system, so I wouldn't put it in same basket as omnipresent new build systems with fancy names. ;)

If you don't want to refactor it to something more sustainable such as STL, it's your choice. I guess I'll write my own implementation then. I just didn't wanted to do everything from scratch by myself... again.

**Comment by msharov** [comment]
Since you only require support for Amiga IFF files, there is no reason to support both types of endianness. Using the EA85 spec with big endian numbers and 2-byte alignment as the only supported format is quite appropriate in your application. For that, you can build libiff using --with-bigendian and --with-2grain configure switches and it will work just fine with the current release, no changes necessary.

As for using plain STL, I already explained that this is much more than simple "refactoring". Streams are a large and complex part of uSTL and I can attest that rewriting them is not a trivial undertaking, having done it myself several times already.

If you are thus trying to add IFF support to the ACE engine itself, presumably for loading data files from the games that use it, you will require a completely different API anyway to be used in plain C. libiff is C++ and much of the code is there to make loading simple into uSTL containers and other classes implementing uSTL stream support. The parts that read the IFF headers are trivial; after all, the headers are just two ints, so you are unlikely to experience great hardship rewriting that part from scratch.
